"""tables

Revision ID: 4cc4671f4467
Revises: 
Create Date: 2019-05-18 18:33:58.590954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc4671f4467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('creditcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('date_pay', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creditcard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creditcard_id'], ['creditcard.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('payed_with', sa.Enum('CASH', 'DEBIT', 'CREDIT', name='paymenttype'), nullable=True),
    sa.Column('parcels', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'OUTGO', 'TRANSFER', name='transactiontype'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Account_Transaction',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Account_Transaction')
    op.drop_table('transaction')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('creditcard')
    op.drop_table('category')
    # ### end Alembic commands ###
